version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: koodata:dev
    ports:
      - 8000:8000
    networks: 
      - backend
    volumes:
      - .:/workspace/
    tty: true

networks:
  backend:
    driver: bridge
